---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# TS - A collection of QoL functions

<!-- badges: start -->
`r badger::badge_lifecycle("stable")`
`r badger::badge_repostatus("Active")`
`r badger::badge_code_size("TimothySundell/TS")`
`r badger::badge_doi("10.1093/bfgp/elac044", "green")`

<!-- badges: end -->

TS was written to improve the quality of life for its creator, maybe it can help you as well?

It contains a collection of functions that may be relevant people analysing single-cell RNA-sequencing data, and analysing Ig(BCR)/TCR-sequences. 

**Please** give our method article a look at the **DOI** button above.
It shows the importance of removing BCR/TCR genes prior to performing unsupervised clustering and downstream analyses of scRNA-seq data containing lymphocytes.

***

## Installation

To install the latest version of the TS package:

``` r
devtools::install_github(TimothySundell/TS)
```

***

## Comments from the author

My plan is to keep this repository updated as much as possible. 
If something is not working, please post in the *Issues* section.

As of now, the package does not pass *R CMD CHECK* as the tidyverse way of coding leaves me a lot of unlinked global variables to reference.
Will maybe be fixed in the future.
